# Generated by Django 5.2.17 on 2026-09-24 01:49

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0002_fornecedor"),
        ("obras", "0001_initial"),
        ("orcamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="data"),
                ),
                (
                    "prazo_resposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="prazo de resposta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
            ],
            options={
                "verbose_name": "cotação",
                "verbose_name_plural": "cotações",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemSolicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "data_necessidade",
                    models.DateField(
                        blank=True, null=True, verbose_name="necessário até"
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orcamento.etapa",
                        verbose_name="etapa (apropriação)",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.insumo",
                        verbose_name="insumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da solicitação",
                "verbose_name_plural": "itens da solicitação",
            },
        ),
        migrations.CreateModel(
            name="ItemCotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "cotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="suprimentos.cotacao",
                        verbose_name="cotação",
                    ),
                ),
                (
                    "item_solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_cotacao",
                        to="suprimentos.itemsolicitacao",
                        verbose_name="item da solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da cotação",
                "verbose_name_plural": "itens da cotação",
            },
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="data"),
                ),
                (
                    "previsao_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="previsão de entrega"
                    ),
                ),
                (
                    "condicao_pagamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="condição de pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("APROVADO", "Aprovado"),
                            ("PARCIAL", "Entregue parcialmente"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "cotacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="suprimentos.cotacao",
                        verbose_name="cotação de origem",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="cadastros.fornecedor",
                        verbose_name="fornecedor",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="obras.obra",
                        verbose_name="obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido de compra",
                "verbose_name_plural": "pedidos de compra",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="preço unitário",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orcamento.etapa",
                        verbose_name="etapa (apropriação)",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.insumo",
                        verbose_name="insumo",
                    ),
                ),
                (
                    "item_solicitacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="suprimentos.itemsolicitacao",
                        verbose_name="item da solicitação",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="suprimentos.pedidocompra",
                        verbose_name="pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do pedido",
                "verbose_name_plural": "itens do pedido",
            },
        ),
        migrations.CreateModel(
            name="PropostaFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prazo_entrega_dias",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="prazo de entrega (dias)"
                    ),
                ),
                (
                    "condicao_pagamento",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 30/60/90 dias",
                        max_length=100,
                        verbose_name="condição de pagamento",
                    ),
                ),
                (
                    "cotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas",
                        to="suprimentos.cotacao",
                        verbose_name="cotação",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.fornecedor",
                        verbose_name="fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "proposta de fornecedor",
                "verbose_name_plural": "propostas de fornecedores",
            },
        ),
        migrations.CreateModel(
            name="PrecoCotado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="preço unitário",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precos",
                        to="suprimentos.itemcotacao",
                        verbose_name="item",
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precos",
                        to="suprimentos.propostafornecedor",
                        verbose_name="proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "preço cotado",
                "verbose_name_plural": "preços cotados",
            },
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="data"),
                ),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="nº da nota fiscal"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimentos",
                        to="suprimentos.pedidocompra",
                        verbose_name="pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "recebimento",
                "verbose_name_plural": "recebimentos",
                "ordering": ["-data", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemRecebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimentos",
                        to="suprimentos.itempedido",
                        verbose_name="item do pedido",
                    ),
                ),
                (
                    "recebimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="suprimentos.recebimento",
                        verbose_name="recebimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "item recebido",
                "verbose_name_plural": "itens recebidos",
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("APROVADA", "Aprovada"),
                            ("ATENDIDA", "Atendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes",
                        to="obras.obra",
                        verbose_name="obra",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação de compra",
                "verbose_name_plural": "solicitações de compra",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddField(
            model_name="itemsolicitacao",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="suprimentos.solicitacaocompra",
                verbose_name="solicitação",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcotacao",
            constraint=models.UniqueConstraint(
                fields=("cotacao", "item_solicitacao"), name="cotacao_item_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="propostafornecedor",
            constraint=models.UniqueConstraint(
                fields=("cotacao", "fornecedor"), name="cotacao_fornecedor_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="precocotado",
            constraint=models.UniqueConstraint(
                fields=("proposta", "item"), name="preco_proposta_item_unico"
            ),
        ),
    ]
