# Generated by Django 5.2.17 on 2026-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suprimentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidocompra",
            name="primeiro_vencimento",
            field=models.DateField(
                blank=True,
                help_text="Opcional. Data da 1ª parcela da primeira nota; as demais seguem os intervalos da condição.",
                null=True,
                verbose_name="1º vencimento",
            ),
        ),
        migrations.AlterField(
            model_name="pedidocompra",
            name="condicao_pagamento",
            field=models.CharField(
                blank=True,
                help_text='Prazos contados da data da nota: "30/60/90", "28 dias", "3x", "dia 10", "3x dia 10" ou "à vista".',
                max_length=100,
                verbose_name="condição de pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="propostafornecedor",
            name="condicao_pagamento",
            field=models.CharField(
                blank=True,
                help_text='Ex.: "30/60/90", "28 dias", "3x", "dia 10" ou "à vista".',
                max_length=100,
                verbose_name="condição de pagamento",
            ),
        ),
    ]
