# Generated by Django 5.2.17 on 2026-09-26 14:07

import config.anexos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suprimentos", "0002_pedidocompra_primeiro_vencimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recebimento",
            name="arquivo_nota",
            field=models.FileField(
                blank=True,
                help_text="PDF, XML, JPG ou PNG, até 10 MB. Pode ser anexado depois.",
                max_length=255,
                upload_to=config.anexos.caminho_nota,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "xml", "jpg", "jpeg", "png"],
                        message="Envie a nota em PDF, XML, JPG ou PNG.",
                    ),
                    config.anexos.validar_tamanho,
                ],
                verbose_name="arquivo da nota fiscal",
            ),
        ),
    ]
