# Generated by Django 5.2.17 on 2026-09-24 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="descrição"),
                ),
                (
                    "versao",
                    models.PositiveIntegerField(default=1, verbose_name="versão"),
                ),
                ("data_base", models.DateField(verbose_name="data-base dos preços")),
                (
                    "bdi_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="BDI (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASC", "Rascunho"),
                            ("APROV", "Aprovado"),
                            ("CANC", "Cancelado"),
                        ],
                        default="RASC",
                        max_length=5,
                        verbose_name="status",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamentos",
                        to="obras.obra",
                        verbose_name="obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "orçamento",
                "verbose_name_plural": "orçamentos",
                "ordering": ["obra", "-versao"],
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ex.: 01, 01.02, 01.02.03",
                        max_length=30,
                        verbose_name="código",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subetapas",
                        to="orcamento.etapa",
                        verbose_name="etapa pai",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="orcamento.orcamento",
                        verbose_name="orçamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "etapa",
                "verbose_name_plural": "etapas",
                "ordering": ["orcamento", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Deixe em branco para copiar o preço atual da composição ou do insumo.",
                        max_digits=14,
                        verbose_name="preço unitário",
                    ),
                ),
                (
                    "composicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.composicao",
                        verbose_name="composição",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="orcamento.etapa",
                        verbose_name="etapa",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.insumo",
                        verbose_name="insumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do orçamento",
                "verbose_name_plural": "itens do orçamento",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("composicao__isnull", False), ("insumo__isnull", True)
                            ),
                            models.Q(
                                ("composicao__isnull", True), ("insumo__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="item_composicao_ou_insumo",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="orcamento",
            constraint=models.UniqueConstraint(
                fields=("obra", "versao"), name="orcamento_versao_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="etapa",
            constraint=models.UniqueConstraint(
                fields=("orcamento", "codigo"), name="etapa_codigo_unico"
            ),
        ),
    ]
