# Generated by Django 5.2.17 on 2026-09-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_cliente"),
        ("orcamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemorcamento",
            options={
                "ordering": ["pk"],
                "verbose_name": "item do orçamento",
                "verbose_name_plural": "itens do orçamento",
            },
        ),
        migrations.RemoveConstraint(
            model_name="itemorcamento",
            name="item_composicao_ou_insumo",
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código do item na planilha (ex.: 1.2.3).",
                max_length=30,
                verbose_name="código",
            ),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="descricao",
            field=models.CharField(
                blank=True,
                help_text="Para itens avulsos. Com composição ou insumo, pode ficar em branco.",
                max_length=500,
                verbose_name="descrição",
            ),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="unidade_medida",
            field=models.ForeignKey(
                blank=True,
                help_text="Para itens avulsos.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.unidademedida",
                verbose_name="unidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemorcamento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("composicao__isnull", False), ("insumo__isnull", True)),
                    models.Q(("composicao__isnull", True), ("insumo__isnull", False)),
                    models.Q(
                        ("composicao__isnull", True),
                        ("insumo__isnull", True),
                        models.Q(("descricao", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="item_composicao_insumo_ou_avulso",
            ),
        ),
    ]
