# Generated by Django 5.2.17 on 2026-09-24 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=10, unique=True, verbose_name="sigla"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=60, verbose_name="descrição"),
                ),
            ],
            options={
                "verbose_name": "unidade de medida",
                "verbose_name_plural": "unidades de medida",
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MAT", "Material"),
                            ("MO", "Mão de obra"),
                            ("EQP", "Equipamento"),
                            ("SRV", "Serviço"),
                        ],
                        max_length=3,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="preço unitário",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidademedida",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "insumo",
                "verbose_name_plural": "insumos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Composicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidademedida",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "composição",
                "verbose_name_plural": "composições",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ComposicaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coeficiente",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="coeficiente",
                    ),
                ),
                (
                    "composicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cadastros.composicao",
                        verbose_name="composição",
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.insumo",
                        verbose_name="insumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da composição",
                "verbose_name_plural": "itens da composição",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("composicao", "insumo"), name="composicao_insumo_unico"
                    )
                ],
            },
        ),
    ]
