# Generated by Django 5.2.17 on 2026-09-24 02:08

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0003_cliente"),
        ("financeiro", "0001_initial"),
        ("obras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_contrato",
                    models.DateField(
                        default=datetime.date.today, verbose_name="data do contrato"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor total",
                    ),
                ),
                (
                    "indice",
                    models.CharField(
                        choices=[
                            ("NENHUM", "Sem reajuste"),
                            ("INCC", "INCC"),
                            ("IGPM", "IGP-M"),
                            ("IPCA", "IPCA"),
                        ],
                        default="INCC",
                        max_length=6,
                        verbose_name="índice de reajuste",
                    ),
                ),
                (
                    "data_base",
                    models.DateField(
                        blank=True,
                        help_text="Os índices dos meses seguintes a este corrigem o saldo. Em branco: a data do contrato.",
                        verbose_name="data-base do reajuste",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASC", "Em elaboração"),
                            ("ATIVO", "Ativo"),
                            ("DIST", "Distratado"),
                        ],
                        default="RASC",
                        max_length=5,
                        verbose_name="situação",
                    ),
                ),
                (
                    "data_distrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="data do distrato"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "titulo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrato_venda",
                        to="financeiro.titulo",
                        verbose_name="título a receber",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato de venda",
                "verbose_name_plural": "contratos de venda",
                "ordering": ["-data_contrato", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="IndiceEconomico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indice",
                    models.CharField(
                        choices=[("INCC", "INCC"), ("IGPM", "IGP-M"), ("IPCA", "IPCA")],
                        max_length=6,
                        verbose_name="índice",
                    ),
                ),
                (
                    "mes",
                    models.DateField(
                        help_text="Qualquer dia do mês; é guardado o dia 1.",
                        verbose_name="mês de referência",
                    ),
                ),
                (
                    "variacao",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-99"))
                        ],
                        verbose_name="variação (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "índice econômico",
                "verbose_name_plural": "índices econômicos",
                "ordering": ["indice", "-mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indice", "mes"), name="indice_mes_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReajusteContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aplicado_em",
                    models.DateField(
                        default=datetime.date.today, verbose_name="aplicado em"
                    ),
                ),
                (
                    "saldo_antes",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="saldo antes"
                    ),
                ),
                (
                    "saldo_depois",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="saldo depois"
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reajustes",
                        to="comercial.contratovenda",
                        verbose_name="contrato",
                    ),
                ),
                (
                    "indice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comercial.indiceeconomico",
                        verbose_name="índice",
                    ),
                ),
            ],
            options={
                "verbose_name": "reajuste aplicado",
                "verbose_name_plural": "reajustes aplicados",
                "ordering": ["indice__mes"],
            },
        ),
        migrations.CreateModel(
            name="ReajusteParcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor anterior"
                    ),
                ),
                (
                    "valor_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor novo"
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reajustes",
                        to="financeiro.parcela",
                    ),
                ),
                (
                    "reajuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="comercial.reajustecontrato",
                        verbose_name="reajuste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SerieParcelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENT", "Entrada / sinal"),
                            ("MEN", "Mensais"),
                            ("INT", "Intermediárias"),
                            ("CHV", "Chaves"),
                            ("FIN", "Financiamento bancário"),
                        ],
                        max_length=3,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantidade",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor de cada parcela",
                    ),
                ),
                ("primeiro_vencimento", models.DateField(verbose_name="1º vencimento")),
                (
                    "intervalo_meses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = mensal, 6 = semestral, 12 = anual.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="intervalo (meses)",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="comercial.contratovenda",
                        verbose_name="contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "série de parcelas",
                "verbose_name_plural": "condição de pagamento (séries de parcelas)",
                "ordering": ["primeiro_vencimento", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bloco",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="bloco / torre"
                    ),
                ),
                (
                    "andar",
                    models.IntegerField(blank=True, null=True, verbose_name="andar"),
                ),
                (
                    "identificador",
                    models.CharField(
                        help_text="Ex.: 101, Casa 3, Lote 12",
                        max_length=30,
                        verbose_name="unidade",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APTO", "Apartamento"),
                            ("CASA", "Casa"),
                            ("SALA", "Sala comercial"),
                            ("LOJA", "Loja"),
                            ("LOTE", "Lote"),
                            ("VAGA", "Vaga de garagem"),
                        ],
                        default="APTO",
                        max_length=4,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "area_privativa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="área privativa (m²)",
                    ),
                ),
                (
                    "quartos",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="dormitórios"
                    ),
                ),
                (
                    "vagas",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="vagas"
                    ),
                ),
                (
                    "preco_tabela",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="preço de tabela",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISP", "Disponível"),
                            ("RES", "Reservada"),
                            ("VEND", "Vendida"),
                            ("BLOQ", "Bloqueada"),
                        ],
                        default="DISP",
                        max_length=4,
                        verbose_name="situação",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to="obras.obra",
                        verbose_name="empreendimento (obra)",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidade",
                "verbose_name_plural": "unidades",
                "ordering": ["obra", "bloco", "-andar", "identificador"],
            },
        ),
        migrations.AddField(
            model_name="contratovenda",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="comercial.unidade",
                verbose_name="unidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="reajustecontrato",
            constraint=models.UniqueConstraint(
                fields=("contrato", "indice"), name="reajuste_indice_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="unidade",
            constraint=models.UniqueConstraint(
                fields=("obra", "bloco", "identificador"),
                name="unidade_identificador_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratovenda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DIST"), _negated=True),
                fields=("unidade",),
                name="unidade_um_contrato_vigente",
                violation_error_message="Esta unidade já tem um contrato vigente.",
            ),
        ),
    ]
