# Generated by Django 5.2.17 on 2026-09-24 01:59

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0003_cliente"),
        ("obras", "0001_initial"),
        ("orcamento", "0001_initial"),
        ("suprimentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("RECEITA", "Receita"), ("DESPESA", "Despesa")],
                        max_length=7,
                        verbose_name="tipo",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "categoria financeira",
                "verbose_name_plural": "plano financeiro",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="nº")),
                ("vencimento", models.DateField(verbose_name="vencimento")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela",
                "verbose_name_plural": "parcelas",
                "ordering": ["vencimento", "titulo", "numero"],
            },
        ),
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Ex.: Banrisul - conta movimento",
                        max_length=100,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=60, verbose_name="banco"),
                ),
                (
                    "agencia",
                    models.CharField(blank=True, max_length=20, verbose_name="agência"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=30, verbose_name="conta"),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="saldo inicial",
                    ),
                ),
                (
                    "data_saldo_inicial",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="data do saldo inicial",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas",
                        to="cadastros.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "conta bancária",
                "verbose_name_plural": "contas bancárias",
                "ordering": ["empresa", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="Baixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="data"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quanto do saldo da parcela está sendo quitado.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor principal",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="juros",
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="multa",
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="desconto",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baixas",
                        to="financeiro.contabancaria",
                        verbose_name="conta bancária",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baixas",
                        to="financeiro.parcela",
                        verbose_name="parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "baixa",
                "verbose_name_plural": "baixas",
                "ordering": ["-data", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ParcelaPagar",
            fields=[],
            options={
                "verbose_name": "parcela a pagar",
                "verbose_name_plural": "contas a pagar - parcelas e baixas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.parcela",),
        ),
        migrations.CreateModel(
            name="ParcelaReceber",
            fields=[],
            options={
                "verbose_name": "parcela a receber",
                "verbose_name_plural": "contas a receber - parcelas e baixas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.parcela",),
        ),
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PAGAR", "A pagar"), ("RECEBER", "A receber")],
                        max_length=7,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True,
                        help_text="Nº da nota, boleto, contrato...",
                        max_length=50,
                        verbose_name="documento",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        default=datetime.date.today, verbose_name="emissão"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descrição"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financeiro.categoriafinanceira",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cliente",
                        verbose_name="cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.fornecedor",
                        verbose_name="fornecedor",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deixe em branco para despesas e receitas administrativas.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="titulos",
                        to="obras.obra",
                        verbose_name="obra",
                    ),
                ),
                (
                    "recebimento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="titulo",
                        to="suprimentos.recebimento",
                        verbose_name="recebimento de origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "título",
                "verbose_name_plural": "títulos",
                "ordering": ["-data_emissao", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="parcela",
            name="titulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas",
                to="financeiro.titulo",
                verbose_name="título",
            ),
        ),
        migrations.CreateModel(
            name="Apropriacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="percentual (%)",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orcamento.etapa",
                        verbose_name="etapa",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apropriacoes",
                        to="financeiro.titulo",
                        verbose_name="título",
                    ),
                ),
            ],
            options={
                "verbose_name": "apropriação",
                "verbose_name_plural": "apropriações por etapa",
            },
        ),
        migrations.CreateModel(
            name="TituloPagar",
            fields=[],
            options={
                "verbose_name": "título a pagar",
                "verbose_name_plural": "contas a pagar - títulos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.titulo",),
        ),
        migrations.CreateModel(
            name="TituloReceber",
            fields=[],
            options={
                "verbose_name": "título a receber",
                "verbose_name_plural": "contas a receber - títulos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.titulo",),
        ),
        migrations.AddConstraint(
            model_name="titulo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cliente__isnull", True),
                        ("fornecedor__isnull", False),
                        ("tipo", "PAGAR"),
                    ),
                    models.Q(
                        ("cliente__isnull", False),
                        ("fornecedor__isnull", True),
                        ("tipo", "RECEBER"),
                    ),
                    _connector="OR",
                ),
                name="titulo_pessoa_conforme_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcela",
            constraint=models.UniqueConstraint(
                fields=("titulo", "numero"), name="parcela_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="apropriacao",
            constraint=models.UniqueConstraint(
                fields=("titulo", "etapa"), name="apropriacao_etapa_unica"
            ),
        ),
    ]
