# Generated by Django 5.2.17 on 2026-09-26 14:15

import config.anexos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baixa",
            name="arquivo_comprovante",
            field=models.FileField(
                blank=True,
                help_text="Comprovante do pagamento: PDF, JPG ou PNG, até 10 MB.",
                max_length=255,
                upload_to=config.anexos.caminho_comprovante,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"],
                        message="Envie o arquivo em PDF, JPG ou PNG.",
                    ),
                    config.anexos.validar_tamanho,
                ],
                verbose_name="comprovante",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="arquivo_boleto",
            field=models.FileField(
                blank=True,
                help_text="PDF, JPG ou PNG, até 10 MB.",
                max_length=255,
                upload_to=config.anexos.caminho_boleto,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"],
                        message="Envie o arquivo em PDF, JPG ou PNG.",
                    ),
                    config.anexos.validar_tamanho,
                ],
                verbose_name="boleto",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="linha_digitavel",
            field=models.CharField(
                blank=True,
                help_text="Código do boleto, para copiar e colar no banco.",
                max_length=60,
                verbose_name="linha digitável",
            ),
        ),
    ]
