# Generated by Django 5.2.17 on 2026-09-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="cidade"),
                ),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="área construída (m²)",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de início"
                    ),
                ),
                (
                    "data_previsao_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="previsão de término"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLAN", "Em planejamento"),
                            ("AND", "Em andamento"),
                            ("PAR", "Paralisada"),
                            ("CONC", "Concluída"),
                        ],
                        default="PLAN",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obras",
                        to="cadastros.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "obra",
                "verbose_name_plural": "obras",
                "ordering": ["codigo"],
            },
        ),
    ]
