# Generated by Django 5.2.17 on 2026-09-24 02:18

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0003_cliente"),
        ("financeiro", "0001_initial"),
        ("obras", "0001_initial"),
        ("orcamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objeto",
                    models.CharField(
                        help_text="Ex.: Execução de alvenaria da Torre A",
                        max_length=200,
                        verbose_name="objeto",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=datetime.date.today, verbose_name="data do contrato"
                    ),
                ),
                (
                    "data_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="término previsto"
                    ),
                ),
                (
                    "retencao_caucao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Retida em cada medição e devolvida no encerramento.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="caução / retenção técnica (%)",
                    ),
                ),
                (
                    "retencao_inss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="INSS retido (%)",
                    ),
                ),
                (
                    "retencao_iss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="ISS retido (%)",
                    ),
                ),
                (
                    "prazo_pagamento_dias",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Contados a partir da data da medição.",
                        verbose_name="prazo de pagamento (dias)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASC", "Em elaboração"),
                            ("ATIVO", "Ativo"),
                            ("ENC", "Encerrado"),
                            ("CANC", "Cancelado"),
                        ],
                        default="RASC",
                        max_length=5,
                        verbose_name="situação",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "DESPESA"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financeiro.categoriafinanceira",
                        verbose_name="categoria financeira",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_servico",
                        to="cadastros.fornecedor",
                        verbose_name="empreiteiro",
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_servico",
                        to="obras.obra",
                        verbose_name="obra",
                    ),
                ),
                (
                    "titulo_caucao",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrato_caucao",
                        to="financeiro.titulo",
                        verbose_name="título de devolução da caução",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato de empreitada",
                "verbose_name_plural": "contratos de empreitada",
                "ordering": ["-data", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, verbose_name="serviço")),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade contratada",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="preço unitário",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="contratos.contratoservico",
                        verbose_name="contrato",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orcamento.etapa",
                        verbose_name="etapa (apropriação)",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidademedida",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do contrato",
                "verbose_name_plural": "itens do contrato",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Medicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="nº"),
                ),
                (
                    "data",
                    models.DateField(
                        default=datetime.date.today, verbose_name="data da medição"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="período de")),
                ("periodo_fim", models.DateField(verbose_name="até")),
                (
                    "status",
                    models.CharField(
                        choices=[("RASC", "Em elaboração"), ("APROV", "Aprovada")],
                        default="RASC",
                        max_length=5,
                        verbose_name="situação",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicoes",
                        to="contratos.contratoservico",
                        verbose_name="contrato",
                    ),
                ),
                (
                    "titulo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicao",
                        to="financeiro.titulo",
                        verbose_name="título a pagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "medição",
                "verbose_name_plural": "medições",
                "ordering": ["-data", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ItemMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="quantidade medida",
                    ),
                ),
                (
                    "item_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicoes",
                        to="contratos.itemcontrato",
                        verbose_name="serviço",
                    ),
                ),
                (
                    "medicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="contratos.medicao",
                        verbose_name="medição",
                    ),
                ),
            ],
            options={
                "verbose_name": "item medido",
                "verbose_name_plural": "itens medidos",
            },
        ),
        migrations.AddConstraint(
            model_name="medicao",
            constraint=models.UniqueConstraint(
                fields=("contrato", "numero"), name="medicao_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemmedicao",
            constraint=models.UniqueConstraint(
                fields=("medicao", "item_contrato"), name="medicao_item_unico"
            ),
        ),
    ]
